stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Hello, GitLab CI!"

test_job:
  stage: test
  script:
    - echo "Test, GitLab CI!"

deploy_job:
  stage: deploy
  script:
    - echo "Goodbye, GitLab CI!"
